import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import TesterClient from '../components/TesterClient';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />


        <Link href="/2/collections" style={{
          border: '1px solid black',
          borderRadius: '5px',
          padding: '10px',
          margin: '10px',
        }}>
          Collections
        </Link>

        <Link href="/1/collections/0x05" style={{
          border: '1px solid black',
          borderRadius: '5px',
          padding: '10px',
          margin: '10px',
        }}>
          Collection 0x05
        </Link>

        <TesterClient />



      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
